// apps/web-next/src/features/notifications/notifications-page.tsx
'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';

import { formatDate, formatStatus } from '../../lib/formatting/display';
import { safeNotificationUrl, type NotificationItem } from './notifications-api';
import { useNotifications } from './notifications-provider';

export function NotificationsPage() {
  const { load: loadNotifications, markAll: markAllNotifications, markRead: markNotification, refreshUnread } = useNotifications();
  const [filter, setFilter] = useState<'all' | 'unread'>('all');
  const [items, setItems] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [markingAll, setMarkingAll] = useState(false);

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { setItems(await loadNotifications(filter, 50)); await refreshUnread(); }
    catch { setError('Notifications could not be loaded. Please try again.'); }
    finally { setLoading(false); }
  }, [filter, loadNotifications, refreshUnread]);

  useEffect(() => { void load(); }, [load]);

  async function markRead(item: NotificationItem) {
    if (item.readAt) return;
    try {
      const updated = await markNotification(item.id);
      setItems((current) => filter === 'unread' ? current.filter((candidate) => candidate.id !== item.id) : current.map((candidate) => candidate.id === item.id ? updated : candidate));
    } catch { setError('The notification could not be marked as read.'); }
  }

  async function markAll() {
    setMarkingAll(true);
    try {
      await markAllNotifications();
      if (filter === 'unread') setItems([]);
      else { const now = new Date().toISOString(); setItems((current) => current.map((item) => ({ ...item, readAt: item.readAt ?? now }))); }
    } catch { setError('Notifications could not be marked as read.'); }
    finally { setMarkingAll(false); }
  }

  return (
    <div className="page-container workspace-page">
      <header className="page-heading"><div><span className="eyebrow">Notification center</span><h1>Notifications</h1><p>Updates about your reports, lost pets, and possible matches.</p></div><button className="primary-action" disabled={!items.some((item) => item.readAt === null) || markingAll} type="button" onClick={() => void markAll()}>{markingAll ? 'Marking...' : 'Mark all as read'}</button></header>
      <div className="tabs"><button className={filter === 'all' ? 'active' : ''} type="button" onClick={() => setFilter('all')}>All</button><button className={filter === 'unread' ? 'active' : ''} type="button" onClick={() => setFilter('unread')}>Unread</button></div>
      {loading ? <section className="loading-state workspace-state"><span className="loading-pulse" /><p>Loading notifications...</p></section> : error ? <section className="empty-state error-state"><span>!</span><h2>Notifications unavailable</h2><p>{error}</p><button className="primary-action" type="button" onClick={() => void load()}>Retry</button></section> : items.length === 0 ? <section className="empty-state"><span aria-hidden="true">OK</span><h2>You're all caught up</h2><p>No notifications to show.</p></section> : <section className="notification-page-list">{items.map((item) => { const action = safeNotificationUrl(item.actionUrl); return <article className={`notification-panel ${item.readAt ? '' : 'unread'}`} key={item.id}><div><span className="eyebrow">{formatStatus(item.type)}</span><h2>{item.title}</h2><p>{item.message}</p><time dateTime={item.createdAt}>{formatDate(item.createdAt)}</time></div><div className="card-actions">{action ? <Link className="secondary-action" href={action} onClick={() => void markRead(item)}>View</Link> : null}{!item.readAt ? <button className="primary-action" type="button" onClick={() => void markRead(item)}>Mark as read</button> : null}</div></article>; })}</section>}
    </div>
  );
}

// libs/frontend/notifications/src/lib/pages/notifications-page/notifications-page.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';

import { NotificationsApiService, type NotificationResponse } from '@petradar/frontend/core';

@Component({
  selector: 'pr-notifications-page',
  standalone: true,
  imports: [DatePipe, RouterLink],
  styleUrl: './notifications-page.component.css',
  templateUrl: './notifications-page.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NotificationsPageComponent implements OnInit {
  private readonly api = inject(NotificationsApiService);
  readonly errorMessage = signal('');
  readonly filter = signal<'all' | 'unread'>('all');
  readonly items = signal<NotificationResponse[]>([]);
  readonly loading = signal(true);
  readonly markingAll = signal(false);
  readonly markingId = signal<string | null>(null);
  readonly hasUnread = computed(() => this.items().some((item) => item.readAt === null));

  ngOnInit(): void {
    void this.load();
  }

  async load(): Promise<void> {
    this.loading.set(true);
    this.errorMessage.set('');
    try {
      const response = await firstValueFrom(this.api.list(this.filter(), 50));
      this.items.set(response.items);
      await this.api.refreshUnreadCount();
    } catch {
      this.errorMessage.set('Notifications could not be loaded. Please try again.');
    } finally {
      this.loading.set(false);
    }
  }

  setFilter(filter: 'all' | 'unread'): void {
    this.filter.set(filter);
    void this.load();
  }

  async markRead(item: NotificationResponse): Promise<void> {
    if (item.readAt !== null) return;
    this.markingId.set(item.id);
    try {
      const updated = await firstValueFrom(this.api.markAsRead(item.id));
      this.items.update((items) => items.map((candidate) => candidate.id === item.id ? updated : candidate));
      if (this.filter() === 'unread') {
        this.items.update((items) => items.filter((candidate) => candidate.id !== item.id));
      }
      await this.api.refreshUnreadCount();
    } catch {
      this.errorMessage.set('The notification could not be marked as read.');
    } finally {
      this.markingId.set(null);
    }
  }

  async markAllRead(): Promise<void> {
    this.markingAll.set(true);
    try {
      await firstValueFrom(this.api.markAllAsRead());
      if (this.filter() === 'unread') this.items.set([]);
      else this.items.update((items) => items.map((item) => ({ ...item, readAt: item.readAt ?? new Date().toISOString() })));
      await this.api.refreshUnreadCount();
    } catch {
      this.errorMessage.set('Notifications could not be marked as read.');
    } finally {
      this.markingAll.set(false);
    }
  }
}

<section class="notifications-page">
  <header class="page-header">
    <div>
      <p class="eyebrow">Notification Center</p>
      <h1>Notifications</h1>
      <p>Important updates about your reports, matches, and rescue work.</p>
    </div>
    <button type="button" [disabled]="!hasUnread() || markingAll()" (click)="markAllRead()">
      {{ markingAll() ? 'Marking…' : 'Mark all as read' }}
    </button>
  </header>

  <div class="tabs" aria-label="Notification filters">
    <button type="button" [class.active]="filter() === 'all'" (click)="setFilter('all')">All</button>
    <button type="button" [class.active]="filter() === 'unread'" (click)="setFilter('unread')">Unread</button>
  </div>

  @if (loading()) {
    <div class="panel"><p>Loading notifications…</p></div>
  } @else if (errorMessage()) {
    <div class="panel error" role="alert">
      <p>{{ errorMessage() }}</p>
      <button type="button" (click)="load()">Retry</button>
    </div>
  } @else if (items().length === 0) {
    <div class="panel"><h2>You're all caught up</h2><p>No notifications to show.</p></div>
  } @else {
    <div class="notification-list">
      @for (item of items(); track item.id) {
        <article class="panel notification" [class.unread]="item.readAt === null">
          <div>
            <h2>{{ item.title }}</h2>
            <p>{{ item.message }}</p>
            <time [attr.datetime]="item.createdAt">{{ item.createdAt | date: 'medium' }}</time>
          </div>
          <div class="notification-actions">
            @if (item.actionUrl) {
              <a [routerLink]="item.actionUrl" (click)="markRead(item)">View</a>
            }
            @if (item.readAt === null) {
              <button type="button" [disabled]="markingId() === item.id" (click)="markRead(item)">
                {{ markingId() === item.id ? 'Marking…' : 'Mark as read' }}
              </button>
            }
          </div>
        </article>
      }
    </div>
  }
</section>
