// apps/web-next/src/features/notifications/notification-bell.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

import { formatDate } from '../../lib/formatting/display';
import { routes } from '../../lib/routes';
import { safeNotificationUrl, type NotificationItem } from './notifications-api';
import { useNotifications } from './notifications-provider';

export function NotificationBell(){const notifications=useNotifications();const router=useRouter();const[open,setOpen]=useState(false);const[items,setItems]=useState<NotificationItem[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[markingAll,setMarkingAll]=useState(false);
  async function toggle(){const next=!open;setOpen(next);if(next){setLoading(true);setError('');try{setItems(await notifications.load('all',15));await notifications.refreshUnread();}catch{setError('Notifications could not be loaded.');}finally{setLoading(false);}}}
  async function select(item:NotificationItem){try{const updated=item.readAt?item:await notifications.markRead(item.id);setItems((current)=>current.map((candidate)=>candidate.id===updated.id?updated:candidate));setOpen(false);const url=safeNotificationUrl(item.actionUrl);if(url)router.push(url);}catch{setError('The notification could not be opened.');}}
  async function markAll(){setMarkingAll(true);setError('');try{await notifications.markAll();const now=new Date().toISOString();setItems((current)=>current.map((item)=>({...item,readAt:item.readAt??now})));}catch{setError('Notifications could not be marked as read.');}finally{setMarkingAll(false);}}
  return <div className="notification-control"><button className="bell-button" type="button" aria-expanded={open} aria-haspopup="dialog" aria-label={notifications.unreadCount?`Notifications, ${notifications.unreadCount} unread`:'Notifications'} onClick={()=>void toggle()}><span aria-hidden="true">♢</span>{notifications.unreadCount>0?<span className="notification-badge">{notifications.unreadCount>99?'99+':notifications.unreadCount}</span>:null}</button>{open?<section className="notification-dropdown" aria-label="Recent notifications"><header><h2>Notifications</h2><button className="text-action" disabled={notifications.unreadCount===0||markingAll} type="button" onClick={()=>void markAll()}>{markingAll?'Marking…':'Mark all as read'}</button></header><div className="notification-content">{loading?<p>Loading notifications…</p>:error?<div className="feedback feedback-error" role="alert">{error}</div>:items.length===0?<div className="notification-empty"><strong>You're all caught up</strong><span>No notifications to show.</span></div>:items.map((item)=><button className={`notification-item ${item.readAt?'':'unread'}`} key={item.id} type="button" onClick={()=>void select(item)}><span className="unread-indicator"/><span><strong>{item.title}</strong><span>{item.message}</span><time dateTime={item.createdAt}>{formatDate(item.createdAt)}</time></span></button>)}</div><footer><Link href={routes.notifications} onClick={()=>setOpen(false)}>View all notifications</Link></footer></section>:null}</div>;
}

// libs/frontend/core/src/lib/notifications/notification-bell.component.ts
import { DatePipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  inject,
  signal,
} from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { LucideBell } from '@lucide/angular';
import { firstValueFrom } from 'rxjs';

import {
  NotificationsApiService,
  type NotificationResponse,
} from './notifications-api.service.js';

@Component({
  selector: 'pr-notification-bell',
  standalone: true,
  imports: [DatePipe, LucideBell, RouterLink],
  templateUrl: './notification-bell.component.html',
  styleUrl: './notification-bell.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NotificationBellComponent {
  private readonly element = inject(ElementRef<HTMLElement>);
  private readonly router = inject(Router);
  readonly notifications = inject(NotificationsApiService);
  readonly errorMessage = signal('');
  readonly items = signal<NotificationResponse[]>([]);
  readonly loading = signal(false);
  readonly markingAll = signal(false);
  readonly markingId = signal<string | null>(null);
  readonly open = signal(false);

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (this.open() && event.target instanceof Node && !this.element.nativeElement.contains(event.target)) {
      this.close();
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    this.close();
  }

  toggle(): void {
    if (this.open()) {
      this.close();
      return;
    }
    this.open.set(true);
    void this.load();
  }

  close(): void {
    this.open.set(false);
  }

  async load(): Promise<void> {
    this.loading.set(true);
    this.errorMessage.set('');
    try {
      const response = await firstValueFrom(this.notifications.list('all', 15));
      this.items.set(response.items);
      await this.notifications.refreshUnreadCount();
    } catch {
      this.errorMessage.set('Notifications could not be loaded.');
    } finally {
      this.loading.set(false);
    }
  }

  async select(item: NotificationResponse): Promise<void> {
    if (this.markingId() !== null) return;
    this.markingId.set(item.id);
    this.errorMessage.set('');
    try {
      if (item.readAt === null) {
        const updated = await firstValueFrom(this.notifications.markAsRead(item.id));
        this.items.update((items) =>
          items.map((candidate) => candidate.id === item.id ? updated : candidate),
        );
        await this.notifications.refreshUnreadCount();
      }
      this.close();
      if (isSafeInternalUrl(item.actionUrl)) {
        await this.router.navigateByUrl(item.actionUrl);
      }
    } catch {
      this.errorMessage.set('The notification could not be opened.');
    } finally {
      this.markingId.set(null);
    }
  }

  async markAllRead(): Promise<void> {
    if (this.markingAll()) return;
    this.markingAll.set(true);
    this.errorMessage.set('');
    try {
      await firstValueFrom(this.notifications.markAllAsRead());
      const readAt = new Date().toISOString();
      this.items.update((items) => items.map((item) => ({ ...item, readAt: item.readAt ?? readAt })));
      await this.notifications.refreshUnreadCount();
    } catch {
      this.errorMessage.set('Notifications could not be marked as read.');
    } finally {
      this.markingAll.set(false);
    }
  }
}

function isSafeInternalUrl(value: string | null): value is string {
  return value !== null && value.startsWith('/') && !value.startsWith('//');
}

<div class="notification-control">
  <button
    type="button"
    class="bell-button"
    [attr.aria-expanded]="open()"
    aria-haspopup="dialog"
    [attr.aria-label]="notifications.unreadCount() > 0
      ? 'Notifications, ' + notifications.unreadCount() + ' unread'
      : 'Notifications'"
    (click)="toggle()"
  >
    <svg lucideBell size="21" strokeWidth="2" aria-hidden="true"></svg>
    @if (notifications.unreadCount() > 0) {
      <span class="notification-badge" aria-hidden="true">
        {{ notifications.unreadCount() > 99 ? '99+' : notifications.unreadCount() }}
      </span>
    }
  </button>

  @if (open()) {
    <section class="notification-dropdown" aria-label="Recent notifications">
      <header>
        <h2>Notifications</h2>
        <button
          type="button"
          class="text-action"
          [disabled]="notifications.unreadCount() === 0 || markingAll()"
          (click)="markAllRead()"
        >
          {{ markingAll() ? 'Marking...' : 'Mark all as read' }}
        </button>
      </header>

      <div class="notification-content">
        @if (loading()) {
          <div class="state-message">Loading notifications...</div>
        } @else if (errorMessage()) {
          <div class="state-message error" role="alert">
            <span>{{ errorMessage() }}</span>
            <button type="button" class="text-action" (click)="load()">Retry</button>
          </div>
        } @else if (items().length === 0) {
          <div class="state-message">
            <strong>You're all caught up</strong>
            <span>No notifications to show.</span>
          </div>
        } @else {
          <div class="notification-list">
            @for (item of items(); track item.id) {
              <button
                type="button"
                class="notification-item"
                [class.unread]="item.readAt === null"
                [disabled]="markingId() !== null"
                (click)="select(item)"
              >
                <span class="unread-indicator" aria-hidden="true"></span>
                <span class="notification-copy">
                  <strong>{{ item.title }}</strong>
                  <span>{{ item.message }}</span>
                  <time [attr.datetime]="item.createdAt">{{ item.createdAt | date: 'short' }}</time>
                </span>
              </button>
            }
          </div>
        }
      </div>

      <footer>
        <a routerLink="/notifications" (click)="close()">View all notifications</a>
      </footer>
    </section>
  }
</div>
